"""Generate or refresh ``CLAUDE.md`` with grounded context for Claude Code–style agents.

Uses **marker blocks** so automated content can be replaced without clobbering user-written notes:

- ``<!-- octo:grounded-memory:managed:start -->`` … ``<!-- octo:grounded-memory:managed:end -->``
- ``<!-- octo:grounded-memory:user:start -->`` … ``<!-- octo:grounded-memory:user:end />``

Call :meth:`GroundedMemoryManager.sync` before an agent session (CLI: ``python -m claude_bridge.grounded_memory``).
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.parse import unquote, urlparse

# -----------------------------------------------------------------------------
# Markers — content outside managed markers is never overwritten by sync().
# -----------------------------------------------------------------------------

MANAGED_START = "<!-- octo:grounded-memory:managed:start -->"
MANAGED_END = "<!-- octo:grounded-memory:managed:end -->"
USER_START = "<!-- octo:grounded-memory:user:start -->"
USER_END = "<!-- octo:grounded-memory:user:end -->"

_HEADER_NOTICE = """# Claude / agent context (Octo-spork)

The **managed** section below is regenerated by `GroundedMemoryManager` from receipts-style inputs
(user summary, SARIF hotspots). **Your persistent notes** belong in the **user** section at the bottom.

"""


DEFAULT_CODING_STANDARDS: tuple[str, ...] = (
    "No placeholders — implement real logic, real names, and complete error handling.",
    "Add docstrings to public modules, classes, and functions (Google or NumPy style, match repo).",
    "Prefer small, testable changes; keep diffs focused on the task.",
    "Do not commit secrets, tokens, or production credentials.",
    "Follow existing lint/format conventions in this repository.",
)

_DEFAULT_USER_SUMMARY_RELATIVE = (
    ".octo/user_summary.md",
    "USER_SUMMARY.md",
    "docs/USER_SUMMARY.md",
)

_DEFAULT_TRIVY_SARIF_RELATIVE = (
    ".octo-spork-trivy-run/results.sarif",
    ".octo/trivy-results.sarif",
)

_DEFAULT_CODEQL_SARIF_RELATIVE = (
    ".octo/codeql-results.sarif",
    ".octo-spork-codeql/results.sarif",
)


def _sarif_level_rank(level: str | None) -> int:
    normalized = str(level or "warning").lower()
    return {"error": 4, "warning": 3, "note": 2, "none": 1}.get(normalized, 2)


def _uri_to_repo_relative(uri: str) -> str:
    if not uri:
        return ""
    if uri.startswith("file://"):
        parsed = urlparse(uri)
        path = unquote(parsed.path or "")
        return path.lstrip("/")
    return uri.replace("\\", "/")


def iter_sarif_findings(payload: dict[str, Any]) -> list[tuple[int, int, str, str, str]]:
    """Return finding rows as ``(neg_rank, seq, level, location, summary)`` for sorting."""
    rows: list[tuple[int, int, str, str, str]] = []
    seq = 0
    for run in payload.get("runs") or []:
        if not isinstance(run, dict):
            continue
        rules_map: dict[str, dict[str, Any]] = {}
        driver = ((run.get("tool") or {}).get("driver")) or {}
        for rule in driver.get("rules") or []:
            if isinstance(rule, dict) and rule.get("id"):
                rules_map[str(rule["id"])] = rule

        for result in run.get("results") or []:
            if not isinstance(result, dict):
                continue
            seq += 1
            level = str(result.get("level") or "warning")
            rank = _sarif_level_rank(level)
            rule_id = str(result.get("ruleId") or "")
            rule_meta = rules_map.get(rule_id) or {}
            short = rule_meta.get("shortDescription")
            short_txt = str(short.get("text") or "") if isinstance(short, dict) else ""
            rule_name = str(rule_meta.get("name") or short_txt or "")
            msg_obj = result.get("message")
            if isinstance(msg_obj, dict):
                message = str(msg_obj.get("text") or rule_id or "")
            else:
                message = str(msg_obj or "")
            message = message.strip().replace("\n", " ")
            if len(message) > 180:
                message = message[:177] + "..."

            loc_label = "(unknown)"
            locations = result.get("locations") or []
            if isinstance(locations, list) and locations:
                loc0 = locations[0] if isinstance(locations[0], dict) else {}
                phys = loc0.get("physicalLocation") if isinstance(loc0.get("physicalLocation"), dict) else {}
                region = phys.get("region") if isinstance(phys.get("region"), dict) else {}
                al = phys.get("artifactLocation") if isinstance(phys.get("artifactLocation"), dict) else {}
                uri = str(al.get("uri") or "")
                rel_path = _uri_to_repo_relative(uri) or uri or "(unknown file)"
                try:
                    line = int(region.get("startLine") or 0)
                except (TypeError, ValueError):
                    line = 0
                loc_label = f"`{rel_path}`:{line}" if line else str(rel_path)

            rid_disp = rule_id or "(rule)"
            summary = rid_disp if rule_name in {"", rid_disp} else f"{rid_disp} — {rule_name}"
            rows.append((-rank, seq, level.upper(), loc_label, summary))

    rows.sort(key=lambda t: (t[0], t[1]))
    return rows


def format_sarif_hotspots_section(
    sarif_path: Path | None,
    *,
    heading: str,
    limit: int = 14,
) -> str:
    """Compact bullet list of top SARIF findings (Trivy or CodeQL)."""
    if sarif_path is None or not sarif_path.is_file():
        return f"_No SARIF file at expected path — {heading}: skipped._\n"

    try:
        payload = json.loads(sarif_path.read_text(encoding="utf-8", errors="replace"))
    except (OSError, json.JSONDecodeError) as exc:
        return f"_Could not read SARIF ({sarif_path}): {exc}_\n"

    rows = iter_sarif_findings(payload)
    if not rows:
        return "_Scan produced no findings in SARIF (clean or empty run)._\n"

    lines = [f"_{sarif_path.name} — top {min(limit, len(rows))} by severity._\n"]
    for _, _, level, loc, summary in rows[:limit]:
        lines.append(f"- **{level}** {loc} — {summary}")
    lines.append("")
    return "\n".join(lines) + "\n"


def merge_claude_md(existing: str | None, managed_body: str) -> str:
    """Replace or insert the managed block; preserve user-marked or legacy trailing content."""
    managed_block = f"{MANAGED_START}\n{managed_body.rstrip()}\n{MANAGED_END}"

    if existing is None or not existing.strip():
        user_placeholder = "_Add project-specific notes, links, or reminders below._\n"
        return (
            _HEADER_NOTICE
            + "\n"
            + managed_block
            + "\n\n"
            + f"{USER_START}\n{user_placeholder}{USER_END}\n"
        )

    if MANAGED_START in existing and MANAGED_END in existing:
        before, _, rest = existing.partition(MANAGED_START)
        _, _, after_managed = rest.partition(MANAGED_END)
        user_inner = ""
        if USER_START in after_managed and USER_END in after_managed:
            _, _, mid = after_managed.partition(USER_START)
            user_inner, _, _ = mid.partition(USER_END)
        else:
            user_inner = after_managed.strip()

        head = before.strip()
        parts: list[str] = []
        if head:
            parts.append(head)
            parts.append("")
        parts.append(managed_block)
        parts.append("")
        parts.append(f"{USER_START}\n{user_inner.strip()}\n{USER_END}")
        return "\n".join(parts).rstrip() + "\n"

    # Legacy file: treat entire document as user-authored; wrap with markers.
    legacy = existing.strip()
    parts = [_HEADER_NOTICE.strip(), "", managed_block, "", f"{USER_START}\n{legacy}\n{USER_END}"]
    return "\n".join(parts).rstrip() + "\n"


def _load_design_principles(repo_root: Path, explicit: Path | None) -> str:
    if explicit is not None:
        if explicit.is_file():
            return explicit.read_text(encoding="utf-8", errors="replace").strip()
        return f"_Expected design principles file not found: `{explicit}`._"

    for rel in _DEFAULT_USER_SUMMARY_RELATIVE:
        p = repo_root / rel
        if p.is_file():
            return p.read_text(encoding="utf-8", errors="replace").strip()

    return (
        "_No design principles file yet._ Add one at `.octo/user_summary.md` or `USER_SUMMARY.md` "
        "(project goals, architecture boundaries, naming — your **User Summary** for agents)."
    )


def _format_coding_standards(extra: tuple[str, ...]) -> str:
    lines = list(DEFAULT_CODING_STANDARDS)
    lines.extend(extra)
    out: list[str] = []
    for rule in lines:
        s = rule.strip()
        if s:
            out.append(f"- {s}")
    return "\n".join(out) + "\n"


def _discover_sarif(repo_root: Path, candidates: tuple[str, ...]) -> Path | None:
    for rel in candidates:
        p = repo_root / rel
        if p.is_file():
            return p
    return None


@dataclass(frozen=True)
class GroundedMemoryResult:
    """Outcome of :meth:`GroundedMemoryManager.sync`."""

    path: Path
    wrote: bool
    managed_chars: int
    user_chars_preserved: int


@dataclass
class GroundedMemoryManager:
    """Build grounded ``CLAUDE.md`` content from receipts-style inputs and SARIF hotspots."""

    repo_root: Path
    user_summary_path: Path | None = None
    trivy_sarif: Path | None = None
    codeql_sarif: Path | None = None
    hotspot_limit: int = 14
    extra_coding_standards: tuple[str, ...] = field(default_factory=tuple)

    def resolved_repo_root(self) -> Path:
        return self.repo_root.expanduser().resolve()

    def resolve_trivy_sarif(self) -> Path | None:
        if self.trivy_sarif is not None:
            p = self.trivy_sarif.expanduser().resolve()
            return p if p.is_file() else None
        return _discover_sarif(self.resolved_repo_root(), _DEFAULT_TRIVY_SARIF_RELATIVE)

    def resolve_codeql_sarif(self) -> Path | None:
        if self.codeql_sarif is not None:
            p = self.codeql_sarif.expanduser().resolve()
            return p if p.is_file() else None
        return _discover_sarif(self.resolved_repo_root(), _DEFAULT_CODEQL_SARIF_RELATIVE)

    def render_managed_body(self) -> str:
        root = self.resolved_repo_root()
        principles = _load_design_principles(root, self.user_summary_path)
        trivy = self.resolve_trivy_sarif()
        codeql = self.resolve_codeql_sarif()

        trivy_md = format_sarif_hotspots_section(
            trivy,
            heading="Trivy",
            limit=self.hotspot_limit,
        )
        codeql_md = format_sarif_hotspots_section(
            codeql,
            heading="CodeQL",
            limit=self.hotspot_limit,
        )
        standards = _format_coding_standards(self.extra_coding_standards)

        return (
            "## 1. Project design principles (User Summary)\n\n"
            f"{principles}\n\n"
            "## 2. Security hotspots (receipts — Trivy / CodeQL SARIF)\n\n"
            "### Trivy\n\n"
            f"{trivy_md}"
            "### CodeQL\n\n"
            f"{codeql_md}"
            "## 3. Strict coding standards\n\n"
            f"{standards}"
        )

    def sync(self, *, dry_run: bool = False) -> GroundedMemoryResult:
        root = self.resolved_repo_root()
        path = root / "CLAUDE.md"
        existing = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else None
        managed = self.render_managed_body()
        merged = merge_claude_md(existing, managed)

        user_chars = 0
        if USER_START in merged and USER_END in merged:
            _, _, tail = merged.partition(USER_START)
            user_blob, _, _ = tail.partition(USER_END)
            user_chars = len(user_blob.strip())

        if not dry_run:
            path.write_text(merged, encoding="utf-8")

        return GroundedMemoryResult(
            path=path,
            wrote=not dry_run,
            managed_chars=len(managed),
            user_chars_preserved=user_chars,
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate or update CLAUDE.md with grounded memory (managed vs user markers).",
    )
    parser.add_argument(
        "--repo",
        type=Path,
        default=Path("."),
        help="Repository root (default: current directory)",
    )
    parser.add_argument(
        "--user-summary",
        type=Path,
        default=None,
        help="Explicit path to User Summary / design principles markdown",
    )
    parser.add_argument("--trivy-sarif", type=Path, default=None, help="Path to Trivy results.sarif")
    parser.add_argument("--codeql-sarif", type=Path, default=None, help="Path to CodeQL SARIF")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print paths only; do not write CLAUDE.md",
    )
    args = parser.parse_args(argv)

    mgr = GroundedMemoryManager(
        repo_root=args.repo,
        user_summary_path=args.user_summary,
        trivy_sarif=args.trivy_sarif,
        codeql_sarif=args.codeql_sarif,
    )
    result = mgr.sync(dry_run=args.dry_run)
    print(f"CLAUDE.md target: {result.path}")
    print(f"Managed region size: {result.managed_chars} chars; user region ~{result.user_chars_preserved} chars")
    if args.dry_run:
        print("(dry-run — no file written)")
    else:
        print(f"Wrote: {result.wrote}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
